package dev.joseph.ledger.repository;

import dev.joseph.ledger.domain.IdempotencyKey;
import java.time.Instant;
import java.util.Optional;
import java.util.UUID;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.Repository;
import org.springframework.data.repository.query.Param;

/** Extends Repository (not JpaRepository) so only the methods listed here exist. */
public interface IdempotencyKeyRepository extends Repository<IdempotencyKey, Long> {

    <S extends IdempotencyKey> S save(S key);

    /**
     * Inserts the row and sends the INSERT to the database immediately. The key id is generated by the database
     * (IDENTITY), so Spring Data sees a new entity and inserts; it does not first SELECT to check whether the row
     * exists (which would be the check-then-insert race this design avoids). Flushing here means a unique violation
     * is thrown from THIS call, at a known line, not later at commit.
     */
    <S extends IdempotencyKey> S saveAndFlush(S key);

    Optional<IdempotencyKey> findByUserIdAndIdemKey(UUID userId, String idemKey);

    /**
     * Removes this user's row for this key only if it has expired. An expired row still occupies the unique index,
     * so without this a new request reusing an expired key would collide with it for ever. Returns the number of
     * rows deleted (0 or 1). It is a bulk JPQL delete, so it does not touch the persistence context.
     */
    @Modifying
    @Query("delete from IdempotencyKey k where k.userId = :userId and k.idemKey = :idemKey and k.expiresAt <= :now")
    int deleteExpired(@Param("userId") UUID userId, @Param("idemKey") String idemKey, @Param("now") Instant now);
}
